# DON'T EDIT; THIS IS GENERATED BY SYNTHTOOL

from __future__ import absolute_import
import os
import pathlib
import re
import shutil
import warnings

import nox

FLAKE8_VERSION = "flake8==6.1.0"
BLACK_VERSION = "black==22.3.0"
ISORT_VERSION = "isort==5.10.1"
LINT_PATHS = [
  "docs",
  "google",
  "vertexai",
  "tests",
  "noxfile.py",
  "setup.py",
]

DEFAULT_PYTHON_VERSION = "3.8"

UNIT_TEST_PYTHON_VERSIONS = ["3.8", "3.9", "3.10", "3.11", "3.12"]